# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_human_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='human_identifier',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
