# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161029_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
